@WorkerSagaDemo.Api_HostAddress = http://localhost:5041

POST {{WorkerSagaDemo.Api_HostAddress}}/ping
Accept: application/json

###

POST {{WorkerSagaDemo.Api_HostAddress}}/jobs
Accept: application/json

###

GET {{WorkerSagaDemo.Api_HostAddress}}/jobs/{{jobId}}
Accept: application/json

###
